server:
  port: 8082
  servlet:
    context-path: /hospital

spring:
  datasource:
    url:  jdbc:postgresql://host.docker.internal:5400/hospital_db
    username: postgres
    password: Merkel
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect






